###
POST localhost:8080/projects/add
Content-Type: application/json

{
  "name":  "Project first ZALUPA"}

######
POST localhost:8080/projects/add
Content-Type: application/json

{
  "id": 4,
  "name":  "Project first ZALUPA!1fdfdfdfd"}

###

GET localhost:8080/projects
###
###

GET localhost:8080/projects/1
###

GET localhost:8080/projects/search?text=zalupa
###

POST localhost:8080/projects/delete/1

##